name: youni
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  charts_flutter: any
  uuid: any
  rxdart: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: any

flutter:
  
  uses-material-design: true

  fonts:
    - family: SourceSerifPro
      fonts:
        - asset: fonts/SourceSerifPro-Regular.ttf
        - asset: fonts/SourceSerifPro-Semibold.ttf
          weight: 600
        - asset: fonts/SourceSerifPro-Bold.ttf
          weight: 800

    - family: NotoSerif
      fonts:
        - asset: fonts/NotoSerif-Regular.ttf
        - asset: fonts/NotoSerif-Bold.ttf
          weight: 800